deployment:
  tasks:
    - export DEPLOYPATH=/home/studezvd/jali.studenterb.co.za/
    - /opt/cpanel/ea-nodejs16/bin/npm install
    - /opt/cpanel/ea-nodejs16/bin/npx ng build --configuration production --output-path dist
    - /bin/cp -R dist/* $DEPLOYPATH
