deployment:
  tasks:
    - export DEPLOYPATH=/home/studezvd/jali.studenterb.co.za/
    - echo "Deployment working!" > $DEPLOYPATH/test.txt
    # - /opt/cpanel/ea-nodejs16/bin/npm install
    # - /opt/cpanel/ea-nodejs16/bin/npm install -g @angular/cli
    # - /opt/cpanel/ea-nodejs16/bin/ng version
    # - /opt/cpanel/ea-nodejs16/bin/npx ng build --configuration production --output-path dist
    # - /bin/cp -R dist/* $DEPLOYPATH
    - echo "=== Running npm install ===" >> $DEPLOYPATH/deploy.log 2>&1
    - /opt/cpanel/ea-nodejs16/bin/npm install >> $DEPLOYPATH/deploy.log 2>&1
    - echo "=== Running ng build ===" >> $DEPLOYPATH/deploy.log 2>&1
    - /opt/cpanel/ea-nodejs16/bin/npx ng build --configuration production --output-path dist >> $DEPLOYPATH/deploy.log 2>&1
    - echo "=== Copying files to public_html ===" >> $DEPLOYPATH/deploy.log 2>&1
    - /bin/cp -R dist/* $DEPLOYPATH >> $DEPLOYPATH/deploy.log 2>&1
    - echo "=== Deployment finished at $(date) ===" >> $DEPLOYPATH/deploy.log 2>&1
