deployment:
  tasks:
    - export DEPLOYPATH=/home/USERNAME/public_html/
    - /opt/cpanel/ea-nodejs16/bin/npm install
    - /opt/cpanel/ea-nodejs16/bin/npx ng build --configuration production --output-path dist
    - /bin/cp -R dist/* $DEPLOYPATH
