deployment:
  tasks:
    - export DEPLOYPATH=/home/studezvd/jali.studenterb.co.za/
    - echo "Deployment working!" > $DEPLOYPATH/test.txt
    # - /opt/cpanel/ea-nodejs16/bin/npm install
    # - /opt/cpanel/ea-nodejs16/bin/npm install -g @angular/cli
    # - /opt/cpanel/ea-nodejs16/bin/ng version
    # - /opt/cpanel/ea-nodejs16/bin/npx ng build --configuration production --output-path dist
    # - /bin/cp -R dist/* $DEPLOYPATH
    deployment:
  tasks:
    - export DEPLOYPATH=/home/USERNAME/public_html/
    - cd frontend   # remove if Angular project is in repo root

    # Log Node & NPM versions
    - echo "=== Checking Node & NPM versions ===" >> $DEPLOYPATH/deploy.log 2>&1
    - /opt/cpanel/ea-nodejs16/bin/node -v >> $DEPLOYPATH/deploy.log 2>&1
    - /opt/cpanel/ea-nodejs16/bin/npm -v >> $DEPLOYPATH/deploy.log 2>&1

    # Try installing Angular CLI (if not available globally)
    - echo "=== Installing Angular CLI (if needed) ===" >> $DEPLOYPATH/deploy.log 2>&1
    - /opt/cpanel/ea-nodejs16/bin/npm install -g @angular/cli >> $DEPLOYPATH/deploy.log 2>&1

    # Run npm install for your project
    - echo "=== Running npm install ===" >> $DEPLOYPATH/deploy.log 2>&1
    - /opt/cpanel/ea-nodejs16/bin/npm install >> $DEPLOYPATH/deploy.log 2>&1

    # Run Angular build
    - echo "=== Running ng build ===" >> $DEPLOYPATH/deploy.log 2>&1
    - /opt/cpanel/ea-nodejs16/bin/npx ng build --configuration production --output-path dist >> $DEPLOYPATH/deploy.log 2>&1

    # Copy build output to public_html
    - echo "=== Copying files to public_html ===" >> $DEPLOYPATH/deploy.log 2>&1
    - /bin/cp -R dist/* $DEPLOYPATH >> $DEPLOYPATH/deploy.log 2>&1

    - echo "=== Deployment finished at $(date) ===" >> $DEPLOYPATH/deploy.log 2>&1

